services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REMOTE_CHROME_HOST=selenium-chrome
      - REMOTE_CHROME_PORT=4444
  selenium-chrome:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
    shm_size: 2gb
